package v1

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/donbader/agent-sandbox/internal/config"
	"github.com/donbader/agent-sandbox/internal/envvar"
	"github.com/donbader/agent-sandbox/internal/plugin"
)

// WriteEnvExample generates a .env.example file at the project root containing
// all environment variable references discovered across all agents.
func WriteEnvExample(projectDir string, entries []ComposeAgentEntry) error {
	seen := map[string]bool{}

	for _, entry := range entries {
		collectEnvVars(entry.Config, entry.Contribs, seen)
	}

	if len(seen) == 0 {
		return nil
	}

	var vars []string
	for v := range seen {
		vars = append(vars, v)
	}
	sort.Strings(vars)

	var sb strings.Builder
	sb.WriteString("# Environment variables for agent-sandbox\n")
	sb.WriteString("# Generated by: agent-sandbox generate\n")
	sb.WriteString("# Copy to .env and fill in values\n\n")
	for _, v := range vars {
		sb.WriteString(fmt.Sprintf("%s=\n", v))
	}

	return os.WriteFile(filepath.Join(projectDir, ".env.example"), []byte(sb.String()), 0644)
}

// collectEnvVars scans a single agent's config and plugin contributions for ${VAR} references.
func collectEnvVars(cfg *config.Config, contribs *plugin.Contributions, seen map[string]bool) {
	// From user gateway config (legacy services)
	for _, svc := range cfg.Gateway.Services {
		for _, value := range svc.Headers {
			for _, ev := range envvar.ExtractAll(value) {
				seen[ev] = true
			}
		}
	}

	// From egress rules (new format)
	for _, rule := range cfg.Gateway.Egress {
		for _, value := range rule.Headers {
			for _, ev := range envvar.ExtractAll(value) {
				seen[ev] = true
			}
		}
	}

	// From plugin contributions (header-based)
	if contribs != nil {
		for _, svc := range contribs.Gateway.Services {
			for _, value := range svc.Headers {
				for _, ev := range envvar.ExtractAll(value) {
					seen[ev] = true
				}
			}
		}
	}

	// From plugin installation options (${VAR} references)
	for _, inst := range cfg.Installations {
		scanOptionsForEnvVars(inst.Options, seen)
	}
}

// scanOptionsForEnvVars recursively scans plugin options for ${VAR} references.
func scanOptionsForEnvVars(opts map[string]any, seen map[string]bool) {
	for _, v := range opts {
		scanValueForAllEnvVars(v, seen)
	}
}

func scanValueForAllEnvVars(v any, seen map[string]bool) {
	switch val := v.(type) {
	case string:
		for _, ev := range envvar.ExtractAll(val) {
			seen[ev] = true
		}
	case map[string]any:
		for _, nested := range val {
			scanValueForAllEnvVars(nested, seen)
		}
	case []any:
		for _, item := range val {
			scanValueForAllEnvVars(item, seen)
		}
	}
}
